version: "3.9"
services:
  auth:
    build:
      context: ../brainbattle-auth
      dockerfile: Dockerfile
    env_file:
      - ../brainbattle-auth/.env
    ports: ["3000:3000"]
    networks: [bbnet]

  core:
    build:
      context: ./brainbattle-core
    env_file:
      - ./brainbattle-core/.env
    ports: ["3001:3001"]
    depends_on: [auth, db]
    networks: [bbnet]

  messaging:
    build:
      context: ./brainbattle-messaging
    env_file:
      - ./brainbattle-messaging/.env
    ports: ["3002:3002"]
    depends_on: [auth, db, redis]
    networks: [bbnet]

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: brainbattle
    ports: ["5432:5432"]
    networks: [bbnet]

  redis:
    image: redis:7
    ports: ["6379:6379"]
    networks: [bbnet]

networks:
  bbnet: {}
